<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../../../src/Hana.Application/Hana.Application.csproj" />
    <ProjectReference Include="../../../src/Hana.Infrastructure/Hana.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>
</Project>
