import { useEffect,useState } from "react";
import { AppState,BackHandler,Image,Pressable,ScrollView,StyleSheet,Text,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as Crypto from "expo-crypto";
import { NativeOrdersController,initialNativeOrdersState } from "./buyer-orders-controller.ts";
import type { MobileCommerceClient } from "./mobile-commerce.ts";
import { colors } from "./theme";
const labels={PAID:"ثبت و پرداخت شده",PREPARING:"در حال آماده‌سازی",READY_FOR_PICKUP:"آماده دریافت حضوری",COLLECTED:"دریافت شده",CANCELLED:"لغو شده"};
const rial=(n:number)=>new Intl.NumberFormat("fa-IR").format(n)+" ریال";
const rtl={textAlign:"right",writingDirection:"rtl",fontFamily:"Vazirmatn_400Regular"} as const;
/** Operational order views reuse the native commerce tokens; no matching Figma order frame was found. */
export function BuyerOrdersScreen({api,selectedId,onBack,onLogin}:{api:MobileCommerceClient;selectedId:string|null;onBack:()=>void;onLogin:()=>void}){
 const [state,setState]=useState(()=>initialNativeOrdersState(selectedId));const [controller]=useState(()=>new NativeOrdersController(api,Crypto.randomUUID,setState,selectedId));
 useEffect(()=>{controller.start();const sub=AppState.addEventListener("change",s=>{if(s==="active")void controller.refresh();});return()=>{sub.remove();controller.stop();};},[controller]);
 const locked=state.busy||!!state.intent;const back=()=>{if(locked)return;if(state.selectedId)void controller.open(null);else onBack();};
 useEffect(()=>{const sub=BackHandler.addEventListener("hardwareBackPress",()=>{back();return true;});return()=>sub.remove();});
 const button=(label:string,run:()=>void,disabled=false,selected=false)=><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled,selected}} disabled={disabled} onPress={run} style={[styles.button,disabled&&{opacity:.5}]}><Text style={styles.buttonText}>{selected?"✓ ":""}{label}</Text></Pressable>;
 const o=state.order;
 return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Image source={require("../assets/hana-cart-logo.png")} resizeMode="contain" style={{width:145,height:48}} accessibilityLabel="حنا"/>{button("بازگشت",back,locked)}</View><Text style={styles.title}>{state.selectedId?"جزئیات سفارش":"سفارش‌های من"}</Text>
 {state.error?<View style={styles.card}><Text accessibilityRole="alert" style={styles.text}>{state.error.message}</Text>{state.error.status===401?button("ورود برای مشاهده سفارش‌ها",onLogin):button("تلاش دوباره",()=>void controller.refresh(),locked)}</View>:state.busy&&!o?<Text style={styles.text}>در حال دریافت سفارش‌ها…</Text>:o?<View style={styles.card}><Text style={styles.heading}>{labels[o.state]}</Text><Text selectable style={styles.text}>شناسه: {o.id}</Text><Text style={styles.text}>{new Date(o.createdAtUtc).toLocaleString("fa-IR")}</Text>{o.items.map(i=><Text key={i.productId} style={styles.text}>{i.productName??"قلم سفارش قدیمی"} · {i.quantity} عدد · {rial(i.quantity*i.unitPriceRial)}</Text>)}<Text style={styles.text}>جمع: {rial(o.totalRial)}</Text><Text style={styles.text}>نقدی: {rial(o.cashPaidRial)} · اعتبار: {rial(o.creditPaidRial)}</Text><Text style={styles.text}>وضعیت بازپرداخت ثبت‌شده: {o.refundState}</Text>
 {["PAID","PREPARING","READY_FOR_PICKUP"].includes(o.state)&&button("لغو سفارش",()=>void controller.change("cancel"),locked)}
 {o.state==="READY_FOR_PICKUP"&&<>{button("سفارش را از فروشگاه تحویل گرفته‌ام",()=>controller.consent(!state.received),locked,state.received)}{button("تأیید دریافت حضوری",()=>void controller.change("pickup-confirmation"),locked||!state.received)}</>}
 {button("دریافت وضعیت تازه",()=>void controller.refresh(),locked)}</View>:state.orders?<><Text style={styles.text}>صفحه {state.page}</Text>{state.orders.length===0&&<Text style={styles.text}>{state.page===1?"هنوز سفارشی ثبت نکرده‌اید.":"در این صفحه سفارشی وجود ندارد."}</Text>}{state.orders.map(order=><View key={order.id} style={styles.card}><Text style={styles.heading}>{labels[order.state]}</Text><Text style={styles.text}>{new Date(order.createdAtUtc).toLocaleString("fa-IR")} · {rial(order.totalRial)}</Text>{button("جزئیات سفارش "+order.id,()=>void controller.open(order.id),locked)}</View>)}{button("صفحه قبل",()=>void controller.page(-1),locked||state.page===1)}{button("صفحه بعد",()=>void controller.page(1),locked||state.orders.length<20||state.page>=10000)}</>:null}
 {state.message!==""&&<Text accessibilityLiveRegion="polite" style={styles.text}>{state.message}</Text>}{state.intent&&<View style={styles.card}><Text style={styles.text}>نتیجه درخواست تأیید نشده؛ همان درخواست را دوباره بررسی کنید.</Text>{button("بررسی نتیجه درخواست قبلی",()=>void controller.retry(),state.busy)}</View>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},content:{padding:20,gap:20,width:"100%",maxWidth:560,alignSelf:"center"},header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",minHeight:80},title:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:26,color:colors.charcoal},heading:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:18,color:colors.teal},text:{...rtl,fontSize:14,lineHeight:26,color:colors.charcoal},card:{backgroundColor:colors.surface,borderColor:colors.beige,borderWidth:1,borderRadius:16,padding:20,gap:12},button:{minHeight:44,borderWidth:1,borderColor:colors.teal,borderRadius:12,padding:12,justifyContent:"center"},buttonText:{...rtl,fontFamily:"Vazirmatn_700Bold",textAlign:"center",color:colors.teal}});
