import { useEffect,useRef,useState } from "react";
import { AppState,BackHandler,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as Crypto from "expo-crypto";
import { NativeIncidentsController,initialNativeIncidentsState,reportWindowOpen } from "./buyer-incidents-controller.ts";
import { chooseIncidentPhoto } from "./incident-photo.ts";
import type { MobileCommerceClient } from "./mobile-commerce.ts";
import { normalizeDigits } from "./phone.ts";
import { colors } from "./theme";
const rtl={textAlign:"right",writingDirection:"rtl",fontFamily:"Vazirmatn_400Regular"} as const;
const labels={UNDER_REVIEW:"در حال بررسی پشتیبانی",REJECTED:"گزارش رد شده",AWAITING_RETURN:"منتظر تحویل کالای مرجوعی",RESOLVED:"رسیدگی انجام شده",COLLECTED:"کالای مرجوعی تحویل شده",CUSTOMER_UNAVAILABLE_VERIFIED:"عدم دسترسی به خریدار تأیید شده"};
/** Operational incident views reuse existing commerce tokens; no matching Figma frame was found. */
export function BuyerIncidentsScreen({api,orderId,onBack,onLogin}:{api:MobileCommerceClient;orderId:string|null;onBack:()=>void;onLogin:()=>void}){
 const [state,setState]=useState(initialNativeIncidentsState),[now,setNow]=useState(Date.now),[picking,setPicking]=useState(false),[photoError,setPhotoError]=useState("");const mounted=useRef(true),pickingRef=useRef(false);
 const [controller]=useState(()=>new NativeIncidentsController(api,Crypto.randomUUID,setState,orderId));
 useEffect(()=>{mounted.current=true;controller.start();const app=AppState.addEventListener("change",s=>{if(s==="active"&&!pickingRef.current)void controller.refresh();});const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{mounted.current=false;app.remove();clearInterval(timer);controller.stop();};},[controller]);
 const locked=state.busy||!!state.intent||picking;
 useEffect(()=>{const sub=BackHandler.addEventListener("hardwareBackPress",()=>{if(!locked)onBack();return true;});return()=>sub.remove();},[locked,onBack]);
 const button=(label:string,run:()=>void,disabled=false,selected=false)=><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled,selected}} disabled={disabled} onPress={run} style={[styles.button,disabled&&{opacity:.5},selected&&styles.selected]}><Text style={[styles.buttonText,selected&&{color:colors.surface}]}>{label}</Text></Pressable>;
 async function pick(){if(locked)return;pickingRef.current=true;setPicking(true);setPhotoError("");try{const photo=await chooseIncidentPhoto();if(mounted.current&&photo)controller.edit({photo});}catch(e){if(mounted.current)setPhotoError(e instanceof Error?e.message:"انتخاب عکس انجام نشد؛ دوباره تلاش کنید.");}finally{pickingRef.current=false;if(mounted.current){setPicking(false);void controller.refresh();}}}
 const d=state.draft,o=state.order,open=reportWindowOpen(o,now);
 return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Image source={require("../assets/hana-cart-logo.png")} resizeMode="contain" style={{width:145,height:48}} accessibilityLabel="حنا"/>{button("بازگشت",onBack,locked)}</View><Text style={styles.title}>گزارش‌ها و مرجوعی‌های من</Text><Text style={styles.text}>گزارش مشکل تا یک ساعت پس از دریافت سفارش ثبت می‌شود. نتیجه بررسی و بازپرداخت را پشتیبانی تعیین می‌کند.</Text>
 {state.error?<View style={styles.card}><Text accessibilityRole="alert" style={styles.text}>{state.error.message}</Text>{state.error.status===401?button("ورود برای مشاهده گزارش‌ها",onLogin):button("تلاش دوباره",()=>void controller.refresh(),locked)}</View>:state.busy&&!state.incidents?<Text style={styles.text}>در حال دریافت گزارش‌ها…</Text>:<>
 {o&&<View style={styles.card}><Text style={styles.heading}>گزارش مشکل سفارش</Text><Text selectable style={styles.text}>شناسه سفارش: {o.id}</Text>{open?<><Text style={styles.text}>مهلت باقی‌مانده: {Math.max(0,Math.ceil((Date.parse(o.receivedAtUtc!)+3600000-now)/60000))} دقیقه</Text>{o.incidentItems.filter(i=>i.quantity>i.refundedQuantity).map(i=><View key={i.id}>{button(i.productName??"قلم سفارش قدیمی",()=>controller.edit({itemId:i.id,quantity:1}),locked,d.itemId===i.id)}</View>)}{button("کالای آسیب‌دیده",()=>controller.edit({type:"DAMAGED_ITEM"}),locked,d.type==="DAMAGED_ITEM")}{button("کالای کسری",()=>controller.edit({type:"MISSING_ITEM"}),locked,d.type==="MISSING_ITEM")}<Text style={styles.text}>تعداد اقلام دارای مشکل</Text><TextInput accessibilityLabel="تعداد اقلام دارای مشکل" editable={!locked} keyboardType="number-pad" maxLength={3} value={d.quantity?String(d.quantity):""} onChangeText={v=>controller.edit({quantity:Number(normalizeDigits(v))})} style={styles.input}/>{d.photo&&<Image source={{uri:d.photo.uri}} resizeMode="contain" accessibilityLabel="پیش‌نمایش عکس مدرک" style={{width:"100%",height:180}}/>}{button(picking?"در حال آماده‌سازی عکس…":"انتخاب عکس مدرک از گالری",()=>void pick(),locked)}{d.photo&&button("حذف عکس انتخاب‌شده",()=>controller.edit({photo:null}),locked)}{photoError!==""&&<Text accessibilityRole="alert" style={styles.text}>{photoError}</Text>}{button("ثبت گزارش برای بررسی پشتیبانی",()=>void controller.report(),locked||!controller.canReport())}</>:<Text style={styles.text}>{o.receivedAtUtc?"مهلت ثبت گزارش این سفارش تمام شده است؛ گزارش‌های قبلی همچنان قابل پیگیری هستند.":"پس از تأیید دریافت سفارش می‌توانید مشکل کالا را گزارش کنید."}</Text>}</View>}
 {state.incidents&&<><Text style={styles.heading}>همه گزارش‌های ثبت‌شده · صفحه {state.page}</Text>{state.incidents.length===0&&<Text style={styles.text}>{state.page===1?"هنوز گزارشی ثبت نشده است.":"در این صفحه گزارشی وجود ندارد."}</Text>}{state.incidents.map(i=><View key={i.id} style={styles.card}><Text style={styles.heading}>{labels[i.state]}</Text><Text style={styles.text}>{i.type==="DAMAGED_ITEM"?"کالای آسیب‌دیده":"کالای کسری"} · {i.quantity} عدد</Text><Text selectable style={styles.text}>سفارش: {i.orderId}</Text><Text style={styles.text}>ثبت: {new Date(i.reportedAtUtc).toLocaleString("fa-IR")}</Text><Text style={styles.text}>بازپرداخت ثبت‌شده: {new Intl.NumberFormat("fa-IR").format(i.refundRial)} ریال</Text>{i.returnDueAtUtc&&<Text style={styles.text}>مهلت جمع‌آوری: {new Date(i.returnDueAtUtc).toLocaleString("fa-IR")}</Text>}{i.state==="AWAITING_RETURN"&&<>{button("کالای مرجوعی را تحویل داده‌ام",()=>controller.consent(state.returnConsent===i.id?null:i.id),locked,state.returnConsent===i.id)}{button("تأیید تحویل کالای مرجوعی",()=>void controller.confirmReturn(i.id),locked||state.returnConsent!==i.id)}</>}</View>)}{button("صفحه قبل",()=>void controller.page(-1),locked||state.page===1)}{button("صفحه بعد",()=>void controller.page(1),locked||state.incidents.length<20||state.page>=10000)}{button("دریافت وضعیت تازه",()=>void controller.refresh(),locked)}</>}
 </>}{state.message!==""&&<Text accessibilityLiveRegion="polite" style={styles.text}>{state.message}</Text>}{state.intent&&<View style={styles.card}><Text style={styles.text}>نتیجه درخواست قبلی تأیید نشده؛ همان درخواست را دوباره بررسی کنید.</Text>{button("بررسی نتیجه درخواست قبلی",()=>void controller.retry(),state.busy)}</View>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},content:{padding:20,gap:20,width:"100%",maxWidth:560,alignSelf:"center"},header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",minHeight:80},title:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:26,color:colors.charcoal},heading:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:18,color:colors.teal},text:{...rtl,fontSize:14,lineHeight:26,color:colors.charcoal},card:{backgroundColor:colors.surface,borderColor:colors.beige,borderWidth:1,borderRadius:16,padding:20,gap:12},button:{minHeight:44,borderWidth:1,borderColor:colors.teal,borderRadius:12,padding:12,justifyContent:"center"},buttonText:{...rtl,fontFamily:"Vazirmatn_700Bold",textAlign:"center",color:colors.teal},selected:{backgroundColor:colors.teal},input:{...rtl,borderColor:colors.beige,borderWidth:1,borderRadius:10,minHeight:48,padding:12,color:colors.charcoal}});
