import { useEffect, useState } from "react";
import { AppState, BackHandler, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as Crypto from "expo-crypto";
import { NativeCheckoutController, initialNativeCheckoutState, nativeCheckoutAmounts } from "./buyer-checkout-controller.ts";
import type { MobileCommerceClient } from "./mobile-commerce.ts";
import { MobileCatalogClient } from "./mobile-catalog.ts";
import { MobileGeographyClient, type GeographyProvince, type GeographyCity } from "./mobile-geography.ts";
import { normalizeDigits } from "./phone.ts";
import { colors } from "./theme";
const logo=require("../assets/hana-cart-logo.png");
const rtl={textAlign:"right",writingDirection:"rtl",fontFamily:"Vazirmatn_400Regular"} as const;
const orderState={PAID:"ثبت و پرداخت شده",PREPARING:"در حال آماده‌سازی",READY_FOR_PICKUP:"آماده دریافت حضوری",COLLECTED:"دریافت شده",CANCELLED:"لغو شده"};
const rial=(v:number)=>new Intl.NumberFormat("fa-IR").format(v)+" ریال";
/** Comparison geometry from draft 723:34; operational checkout controls extend that frame. */
export function BuyerCheckoutScreen({api,onBack,onLogin}:{api:MobileCommerceClient;onBack:()=>void;onLogin:()=>void}) {
 const [state,setState]=useState(initialNativeCheckoutState),[now,setNow]=useState(Date.now);
 const [controller]=useState(()=>new NativeCheckoutController(api,new MobileCatalogClient(process.env.EXPO_PUBLIC_HANA_API_BASE_URL,fetch,__DEV__),Crypto.randomUUID,setState));
 const [geo]=useState(()=>new MobileGeographyClient(process.env.EXPO_PUBLIC_HANA_API_BASE_URL,fetch,__DEV__));
 const [addressForm,setAddressForm]=useState(false),[provinces,setProvinces]=useState<GeographyProvince[]>([]),[cities,setCities]=useState<GeographyCity[]>([]),[province,setProvince]=useState(""),[city,setCity]=useState(""),[addressText,setAddressText]=useState(""),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState(""),[geoError,setGeoError]=useState("");
 useEffect(()=>{controller.start();const app=AppState.addEventListener("change",s=>{if(s==="active")void controller.refresh();});const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(timer);app.remove();controller.stop();};},[controller]);
 useEffect(()=>{const back=BackHandler.addEventListener("hardwareBackPress",()=>{if(!state.busy&&!state.intent)onBack();return true;});return()=>back.remove();},[state.busy,state.intent,onBack]);
 useEffect(()=>{if(!addressForm)return;let active=true;void geo.provinces().then(r=>{if(!active)return;if(r.status==="ok")setProvinces(r.data);else setGeoError("فهرست استان‌ها دریافت نشد؛ فرم را ببندید و دوباره باز کنید.");});return()=>{active=false;};},[geo,addressForm]);
 useEffect(()=>{setCities([]);setCity("");if(!province)return;let active=true;void geo.cities(province).then(r=>{if(!active)return;if(r.status==="ok")setCities(r.data);else setGeoError("فهرست شهرها دریافت نشد؛ استان را دوباره انتخاب کنید.");});return()=>{active=false;};},[geo,province]);
 const locked=state.busy||!!state.intent,amounts=nativeCheckoutAmounts(state,now),q=state.quote,data=state.data;
 const name=(id:string)=>data?.products[id]?.name??"نام کالا فعلاً دریافت نشد";
 const button=(label:string,run:()=>void,disabled=false,selected=false)=><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled,selected}} disabled={disabled} onPress={run} style={[styles.button,selected&&styles.selected,disabled&&{opacity:0.5}]}><Text style={[styles.buttonText,selected&&{color:colors.surface}]}>{label}</Text></Pressable>;
 const addressValid=!!city&&!!addressText.trim()&&!!latitude.trim()&&!!longitude.trim()&&Number.isFinite(Number(latitude))&&Math.abs(Number(latitude))<=90&&Number.isFinite(Number(longitude))&&Math.abs(Number(longitude))<=180;
 return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><ScrollView contentContainerStyle={{flexGrow:1}} keyboardShouldPersistTaps="handled"><View style={styles.header}><Image source={logo} resizeMode="contain" style={styles.logo} accessibilityLabel="حنا"/>{button("بازگشت",onBack,locked)}</View><View style={styles.content}>
 <Text style={styles.eyebrow}>خرید از حنا</Text><Text style={styles.title} accessibilityRole="header">مقایسهٔ پیشنهادها</Text><Text style={styles.text}>پیشنهادهای منتشرشده برای سبد مرجع</Text><View style={styles.notice}><Text style={[styles.text,{color:colors.teal}]}>هر سفارش فقط یک فروشگاه دارد. مقایسه و پیش‌فاکتور، موجودی را رزرو نمی‌کنند. فعلاً فقط دریافت حضوری فعال است.</Text></View>
 {state.error?<View style={styles.card}><Text accessibilityRole="alert" style={styles.text}>{state.error.message}</Text>{state.error.status===401?button("ورود برای ادامه خرید",onLogin):button("تلاش دوباره",()=>void controller.refresh(),state.busy)}</View>:state.busy&&!data?<Text accessibilityLiveRegion="polite" style={styles.text}>در حال دریافت اطلاعات…</Text>:state.order?<View style={styles.card}><Text style={styles.cardTitle}>سفارش ثبت‌شده</Text><Text selectable style={styles.text}>شناسه سفارش: {state.order.id}</Text><Text style={styles.text}>وضعیت: {orderState[state.order.state]}</Text>{state.order.items.map(i=><Text key={i.productId} style={styles.text}>{i.productName??"قلم سفارش"} · {i.quantity} عدد</Text>)}<Text style={styles.text}>جمع: {rial(state.order.totalRial)}</Text><Text style={styles.text}>نقدی: {rial(state.order.cashPaidRial)} · اعتبار: {rial(state.order.creditPaidRial)}</Text>{button("دریافت وضعیت تازه",()=>void controller.refresh(),locked)}</View>:!data?<Text style={styles.text}>در حال دریافت سبد و پیشنهادها…</Text>:<>
 <View style={styles.card}><Text style={styles.cardTitle}>اقلام سبد مرجع</Text>{data.cart.items.length===0&&<Text style={styles.text}>سبد شما خالی است.</Text>}{data.cart.items.map(i=><Text key={i.productId} style={styles.text}>{name(i.productId)} · {i.quantity} عدد</Text>)}</View>
 {data.cart.items.length>0&&data.comparisons.length===0&&<Text style={styles.text}>پیشنهاد قابل تأمین پیدا نشد؛ می‌توانید کالا یا تعداد را در سبد تغییر دهید.</Text>}
 {data.comparisons.map(c=><View key={c.sellerId} style={styles.card}><Text style={styles.cardTitle}>{c.storeName}</Text>{c.available.map(i=><View key={i.productId} style={styles.item}><Text style={styles.itemTitle}>{name(i.productId)}</Text><Text style={styles.text}>قیمت واحد: {rial(i.unitPriceRial)}</Text><Text style={styles.text}>تعداد: {i.quantity}</Text></View>)}{c.unavailable.length>0&&<Text style={styles.text}>ناموجود: {c.unavailable.map(i=>name(i.productId)).join("، ")}</Text>}<Text style={styles.text}>جمع اقلام موجود: {rial(c.itemsTotalRial)}</Text>{button("انتخاب فروشگاه: "+c.storeName,()=>controller.choose({sellerId:c.sellerId}),locked,state.sellerId===c.sellerId)}</View>)}
 {data.comparisons.length>0&&<View style={styles.card}><Text style={styles.cardTitle}>نشانی و نوع خرید</Text>{data.addresses.map(a=><View key={a.id}>{button(a.text,()=>controller.choose({addressId:a.id}),locked,state.addressId===a.id)}</View>)}{data.addresses.length===0&&<Text style={styles.text}>برای ادامه، نشانی ثبت کنید.</Text>}{button(addressForm?"بستن فرم نشانی":"ثبت نشانی جدید",()=>{setGeoError("");setAddressForm(v=>!v);},locked)}
 {addressForm&&<View style={{gap:10}}><Text style={styles.text}>استان</Text>{provinces.map(p=><View key={p.id}>{button(p.name,()=>setProvince(p.id),locked,province===p.id)}</View>)}<Text style={styles.text}>شهر</Text>{cities.map(c=><View key={c.id}>{button(c.name,()=>setCity(c.id),locked,city===c.id)}</View>)}{[["نشانی کامل",addressText,setAddressText],["عرض جغرافیایی",latitude,setLatitude],["طول جغرافیایی",longitude,setLongitude]].map(([label,value,setter])=><TextInput key={label as string} accessibilityLabel={label as string} placeholder={label as string} value={value as string} editable={!locked} maxLength={label==="نشانی کامل"?1000:30} onChangeText={v=>(setter as (v:string)=>void)(label==="نشانی کامل"?v:normalizeDigits(v))} style={styles.input}/>)}<Text style={styles.text}>مختصات را از محل نشانی وارد کنید؛ نقشه و دریافت موقعیت خودکار هنوز متصل نیستند.</Text>{geoError!==""&&<Text accessibilityRole="alert" style={styles.text}>{geoError}</Text>}{button("ذخیره نشانی",()=>void controller.saveAddress(city,addressText,Number(latitude),Number(longitude)),locked||!addressValid)}</View>}
 {button("خرید شخصی",()=>controller.choose({purchaseType:"PERSONAL"}),locked,state.purchaseType==="PERSONAL")}{button("خرید حقوقی / سازمانی",()=>controller.choose({purchaseType:"LEGAL"}),locked,state.purchaseType==="LEGAL")}{button("دریافت پیش‌فاکتور",()=>void controller.quote(),locked||!state.sellerId||!state.addressId)}
 </View>}
 {q&&<View style={styles.card}><Text style={styles.cardTitle}>بازبینی و ثبت سفارش</Text>{q.items.map(i=><Text key={i.productId} style={styles.text}>{name(i.productId)} · {i.quantity} عدد · {rial(i.quantity*i.unitPriceRial)}</Text>)}<Text style={styles.text}>جمع سفارش: {rial(q.itemsTotalRial)}</Text><Text accessibilityLiveRegion="polite" style={styles.text}>{Date.parse(q.expiresAtUtc)>now?"اعتبار پیش‌فاکتور: "+Math.ceil((Date.parse(q.expiresAtUtc)-now)/1000)+" ثانیه":"پیش‌فاکتور منقضی شده؛ پیش‌فاکتور تازه بگیرید."}</Text>
 {state.purchaseType==="PERSONAL"&&<>{button("بدون اعتبار حمایتی",()=>controller.review({creditId:""}),locked,state.creditId==="")}{amounts.credits.map(c=><View key={c.id}>{button("اعتبار حمایتی: "+rial(c.availableRial),()=>controller.review({creditId:c.id}),locked,state.creditId===c.id)}</View>)}</>}
 <Text style={styles.text}>سهم اعتبار: {rial(amounts.credit)} · سهم نقدی: {rial(amounts.cash)}</Text><Text style={styles.text}>کیف پول نقدی: {rial(data.balanceRial)}</Text>{amounts.cash>data.balanceRial&&<Text accessibilityRole="alert" style={styles.text}>موجودی کافی نیست؛ درگاه هنوز فعال نشده است.</Text>}
 {q.unavailable.length>0&&<><Text style={styles.text}>اقلام ناموجود: {q.unavailable.map(i=>name(i.productId)).join("، ")}</Text>{button("در سبد بمانند",()=>controller.review({disposition:"KEEP"}),locked,state.disposition==="KEEP")}{button("بعد از خرید از سبد حذف شوند",()=>controller.review({disposition:"REMOVE"}),locked,state.disposition==="REMOVE")}{button("خرید فقط اقلام موجود را تأیید می‌کنم",()=>controller.review({confirmed:!state.confirmed}),locked,state.confirmed)}</>}
 {button("ثبت سفارش و کسر مبلغ",()=>void controller.place(),!amounts.canPlace)}</View>}
 </>}
 {state.message!==""&&<Text accessibilityLiveRegion="polite" style={styles.text}>{state.message}</Text>}{state.intent&&<View style={styles.card}><Text style={styles.text}>نتیجه درخواست قبلی هنوز تأیید نشده؛ همان درخواست را بررسی کنید.</Text>{button("بررسی نتیجه درخواست قبلی",()=>void controller.retry(),state.busy)}</View>}
 {button("بازگشت به سبد مرجع",onBack,locked)}
 </View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},header:{height:80,paddingHorizontal:20,paddingVertical:14,backgroundColor:colors.surface,flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between"},logo:{width:145,height:48},content:{paddingHorizontal:20,paddingTop:20,paddingBottom:48,gap:20,width:"100%",maxWidth:560,alignSelf:"center"},eyebrow:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:13,color:colors.terracotta},title:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:26,lineHeight:42,color:colors.charcoal},text:{...rtl,fontSize:14,lineHeight:25,color:colors.muted},notice:{backgroundColor:colors.paleTeal,borderRadius:16,paddingHorizontal:20,paddingVertical:18,minHeight:112},card:{backgroundColor:colors.surface,borderColor:colors.beige,borderWidth:1,borderRadius:16,paddingHorizontal:20,paddingVertical:18,gap:10},cardTitle:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:18,lineHeight:30,color:colors.teal},item:{backgroundColor:colors.cream,borderRadius:16,paddingHorizontal:20,paddingVertical:18,gap:10,minHeight:120},itemTitle:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:15,color:colors.charcoal},button:{minHeight:44,borderWidth:1,borderColor:colors.teal,borderRadius:12,paddingHorizontal:10,paddingVertical:10,justifyContent:"center"},buttonText:{...rtl,fontFamily:"Vazirmatn_700Bold",fontSize:14,color:colors.teal,textAlign:"center"},selected:{backgroundColor:colors.teal},input:{...rtl,borderColor:colors.beige,borderWidth:1,borderRadius:10,minHeight:48,padding:12,color:colors.charcoal}});
